--###################QUESTIONS########################
--CUSTOMER1
--
--2. ADD A COLUMN EMAIL
--3. CHANGE THE DATATYPE FROM VARCHAR2(1)
--4. DROP THE COLUM EMAIL.
--5. ADD A COLUMN 'MARITAL STATUS'
--6. RENAME THE ADDRESS COLUMN TO 'CUST_LOCATION'
--
--7. INSERT 10 RECORDS TO CUSTOMER TABLE
--8. UPDATE THE CITY OF THOSE CUSTOMERS FROM 'BANGALORE' TO 'BENGALURU'
--9. DELETE ALL THE CUSTOMER WHOSE MARITAL STATUS IS 'UM'


--CREATING CUSTOMER1 TABLE
CREATE TABLE customer1
(
cust_id INT PRIMARY KEY,
cust_name VARCHAR(15) NOT NULL,
cust_phone NUMBER(10) CHECK(LENGTH(cust_phone)=10),
cust_add VARCHAR(25),
cust_gender VARCHAR2(1) CHECK (cust_gender IN ('M','F')),
cust_city_name VARCHAR(10) NOT NULL,
cust_dob DATE NOT NULL CHECK(cust_dob<'31-DEC-2000')
);

-- TO DROP THE CUSTOMER1 TABLE
DROP TABLE CUSTOMER1;

--2. ADD A COLUMN EMAIL
ALTER TABLE CUSTOMER1 ADD EMAIL VARCHAR(15) UNIQUE;

--DESCRIPTION OF CUSTOMER1 TABLE
DESC CUSTOMER1;

--3. CHANGE THE DATATYPE FROM VARCHAR2(10)
ALTER TABLE CUSTOMER1 MODIFY CUST_GENDER VARCHAR2(10);

--DESCRIPTION OF CUSTOMER1 TABLE
DESC CUSTOMER1;

--4. DROP THE COLUM EMAIL.
ALTER TABLE CUSTOMER1 DROP COLUMN EMAIL;

--5. ADD A COLUMN 'MARITAL STATUS'
ALTER TABLE CUSTOMER1 ADD MARITAL_STATUS VARCHAR2(2) CHECK (MARITAL_STATUS IN('M','UM'));

--6. RENAME THE CUST_ADD COLUMN TO 'CUST_LOCATION'
ALTER TABLE CUSTOMER1 RENAME COLUMN CUST_ADD TO CUST_LOCATION;

--7. INSERT 10 RECORDS TO CUSTOMER TABLE
INSERT INTO CUSTOMER1 VALUES(1, 'SHAILENDRA', '8770065751', 'BTM', 'M', 'BHOPAL', '01-JUL-1996', 'UM');
INSERT INTO CUSTOMER1 VALUES(2, 'NAMITA', '8770999751', 'BTM 2ND STAGE', 'F', 'RAISEN', '19-AUG-1994', 'M');
INSERT INTO CUSTOMER1 VALUES(3, 'SHAILI', '7900065751', 'SOBHAGYA NAGAR', 'M', 'CHANDIGARH', '16-JUL-1992', 'UM');
INSERT INTO CUSTOMER1 VALUES(4, 'PRINC', '9780065751', 'JAYNAGAR', 'M', 'MYSORE', '28-OCT-1994', 'M');
INSERT INTO CUSTOMER1 VALUES(5, 'LOKESH', '9990065751', 'BANARGATTA', 'M', 'SATNA', '21-JUN-1999', 'UM');
INSERT INTO CUSTOMER1 VALUES(6, 'KIRAN', '9999065751', 'VIJAY NAGAR', 'F', 'DELHI', '31-JUL-1997', 'M');
INSERT INTO CUSTOMER1 VALUES(7, 'SURESH', '8777885751', 'RAJAJI NAGAR', 'M', 'PATNA', '28-FEB-1992', 'UM');
INSERT INTO CUSTOMER1 VALUES(8, 'KAMAL', '8770077751', 'EAST CIRCLE', 'M', 'SURAT', '11-APR-1990', 'UM');
INSERT INTO CUSTOMER1 VALUES(9, 'MAHESH', '8771115751', 'LKG', 'M', 'BANGALORE', '14-MAR-1991', 'M');
INSERT INTO CUSTOMER1 VALUES(10, 'RAJ', '8888065751', 'SDM', 'M', 'PUNE', '15-JUL-1992', 'M');

--TO DISPLAY CUSTOMER1 TABLE
SELECT * FROM CUSTOMER1;

--8. UPDATE THE CITY OF THOSE CUSTOMERS FROM 'BANGALORE' TO 'BENGALURU'
UPDATE CUSTOMER1 SET CUST_CITY_NAME='BENGALURU' WHERE CUST_CITY_NAME='BANGALORE';

DESC CUSTOMER1;

--9. DELETE ALL THE CUSTOMER WHOSE MARITAL STATUS IS 'UM'
DELETE FROM CUSTOMER1 WHERE MARITAL_STATUS='UM';

--DISPLAY CUSTOMER1 TABLE
SELECT * FROM CUSTOMER1;


----------STRING FUNCTIONS 

--1.--ASCII
SELECT * FROM CUSTOMER1;

SELECT ASCII(CUST_NAME) FROM CUSTOMER1;
--IT WILL SHOW THE ASCII VALUE OF FIRST CHARACTER OF CUST_NAME
SELECT ASCII('N') FROM DUAL;

--2.--CHR

SELECT RPAD(CUST_NAME, 9,'-') FROM CUSTOMER1;

SELECT LPAD(CUST_NAME, 9,'-') FROM CUSTOMER1;

SELECT TRIM(LEADING 'O' FROM 'OOLADKH') FROM DUAL;

SELECT TRIM(TRAILING 'H' FROM 'OOLADKHHHHHHHHHHH') FROM DUAL;

SELECT TRIM(BOTH 'H' FROM 'HHHHHHHHHHHHHOOLADKHHHHHHHHHHH') FROM DUAL;






