--------------QUERIES USING SET-OPERATORS----------------

SELECT E.ENAME,D.DNAME 
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO(+)

UNION

SELECT E.ENAME,D.DNAME
FROM EMP E,DEPT D
WHERE E.DEPTNO(+)=D.DEPTNO;


--OR--

SELECT E.ENAME, D.DNAME
FROM EMP E FULL OUTER JOIN DEPT D
ON E.DEPTNO=D.DEPTNO;


--------------------
SELECT DISTINCT SAL FROM EMP
WHERE DEPTNO=10

UNION ALL

SELECT DISTINCT SAL FROM EMP
WHERE DEPTNO=20;

INTERSECT

SELECT SAL FROM EMP
WHERE DEPTNO=30;

---------------------------------------

SELECT ENAME 
FROM EMP
WHERE DEPTNO=10

UNION ALL

SELECT ENAME 
FROM EMP
WHERE DEPTNO=20;

---------------------------------------


SELECT SUBSTR('STATE',1) || SUBSTR('KARNATAKA',1)
FROM DUAL
UNION ALL
 SELECT SUBSTR('CAPITAL',1) || SUBSTR('BANGALORE',1)
FROM DUAL;




SELECT 'state',SUBSTR('Karnataka,Bangalore',1,INSTR('Karnataka,Bangalore',',')-1) FROM DUAL
UNION

SELECT 'capital',SUBSTR('Karnataka,Bangalore',INSTR('Karnataka,Bangalore',',')+1) FROM DUAL;

--
--------------------------------------------------------------------------------
CREATE TABLE CALL(
CALL_ID NUMBER PRIMARY KEY,
CALL_DUR TIMESTAMP,
SALE_ID NUMBER REFERENCES SALE(SALE_ID));

INSERT INTO CALL VALUES(111,CURRENT_TIMESTAMP,101);
INSERT INTO CALL VALUES(112,CURRENT_TIMESTAMP,109);
INSERT INTO CALL VALUES(113,CURRENT_TIMESTAMP,102);
INSERT INTO CALL VALUES(114,CURRENT_TIMESTAMP,107);
INSERT INTO CALL VALUES(115,CURRENT_TIMESTAMP,101);
INSERT INTO CALL VALUES(116,CURRENT_TIMESTAMP,102);

SELECT A.PRODUCT_NAME,A.SAL_COUNT,A.SAL_QTY,B.CALL_COUNT,B.CALL_DURA
FROM(SELECT P.PRODUCT_NAME,COUNT(S.SALE_ID) AS SAL_COUNT,SUM(S.QTY) AS SAL_QTY
     FROM PRODUCT_DETAIL P,SALE S
     WHERE P.PRODUCT_ID=S.PRODUCT_ID
     GROUP BY P.PRODUCT_NAME)A,
     (SELECT P.PRODUCT_NAME,COUNT(C.CALL_ID) AS CALL_COUNT,SUM(CALL_TIME) AS CALL_DURA
     FROM PRODUCT_DETAIL P,SALE S,CALL C
     WHERE P.PRODUCT_ID=S.PRODUCT_ID AND S.SALE_ID=C.SALE_ID
     GROUP BY P.PRODUCT_NAME)B
 WHERE A.PRODUCT_NAME=B.PRODUCT_NAME;    
 