CREATE TABLE CITY_1(
CITY_ID NUMBER PRIMARY KEY,
CITY_NAME VARCHAR2(15));

INSERT ALL
INTO CITY_1 VALUES(1,'BHOPAL')
INTO CITY_1 VALUES(2,'PUNE')
INTO CITY_1 VALUES(3,'BANGALORE')
SELECT * FROM DUAL;

CREATE TABLE CUSTOMER_1(
CUST_ID NUMBER PRIMARY KEY,
CUST_NAME VARCHAR2(20),
CUST_GENDER VARCHAR2(9),
CUST_DOB DATE,
CUST_EMAIL VARCHAR2(30),
CITY_ID REFERENCES CITY_1(CITY_ID)
);


INSERT ALL
INTO CUSTOMER_1 VALUES(10,'SHAILENDRAS','MALE','12-04-1994','SHAILENDRA@YAHOO.COM',1)
INTO CUSTOMER_1 VALUES(11,'RAJNI','FEMALE','17-12-1991','RAJNI@YAHOO.COM',2)
INTO CUSTOMER_1 VALUES(12,'RAJESH','MALE','19-07-1999','RAJESH@YAHOO.COM',2)
INTO CUSTOMER_1 VALUES(13,'SONY','FEMALE','28-10-1992','SONY@YAHOO.COM',2)
INTO CUSTOMER_1 VALUES(14,'SOFIYA','FEMALE','06-01-1997','SOFIY@YAHOO.COM',2)
INTO CUSTOMER_1 VALUES(15,'SOBHIT','MALE','08-09-1991','SOBHIT@YAHOO.COM',1)
INTO CUSTOMER_1 VALUES(16,'BUNTY','MALE','22-07-1998','BUNTY@YAHOO.COM',1)
INTO CUSTOMER_1 VALUES(17,'SAIF','MALE','22-03-1999','SAIF@YAHOO.COM',1)
INTO CUSTOMER_1 VALUES(18,'KUNDAN','MALE','19-07-1995','KUNDAN@YAHOO.COM',1)
INTO CUSTOMER_1 VALUES(19,'ADI','MALE','12-03-2000','ADI@YAHOO.COM',1)
INTO CUSTOMER_1 VALUES(20,'MAYANK','MALE','02-10-1993','MAYANK@YAHOO.COM',1)
SELECT * FROM DUAL;


CREATE TABLE STORE_1(
STORE_ID NUMBER(3) PRIMARY KEY,
STORE_NAME VARCHAR2(25),
CITY_ID REFERENCES CITY_1(CITY_ID));

SELECT * FROM STORE_1;

INSERT ALL
INTO STORE_1 VALUES(100,'CHROMA',1)
INTO STORE_1 VALUES(101,'V MART',3)
INTO STORE_1 VALUES(102,'HYPER CITY',3)
INTO STORE_1 VALUES(103,'MED PLUS',1)
INTO STORE_1 VALUES(104,'D MART',1)
SELECT * FROM DUAL;

CREATE TABLE SALES_1(
SALE_ID NUMBER(3) PRIMARY KEY,
SALE_DATE DATE,
SALE_QTY NUMBER (5),
SALE_AMOUNT NUMBER (10),
CUST_ID REFERENCES CUSTOMER_1(CUST_ID),
STORE_ID REFERENCES STORE_1(STORE_ID),
PROD_ID REFERENCES PRODUCT_1(PROD_ID));

INSERT INTO SALES_1 VALUES(901,'27-02-2020',50,50000,10,100,200);
INSERT INTO SALES_1 VALUES(901,'27-02-2020',50,50000,10,100,200);
INSERT INTO SALES_1 VALUES(901,'27-02-2020',50,50000,10,100,200);
INSERT INTO SALES_1 VALUES(901,'27-02-2020',50,50000,10,100,200);
INSERT INTO SALES_1 VALUES(901,'27-02-2020',50,50000,10,100,200);
INSERT INTO SALES_1 VALUES(901,'27-02-2020',50,50000,10,100,200);
INSERT INTO SALES_1 VALUES(901,'27-02-2020',50,50000,10,100,200);





SELECT * FROM SALES_1;
DESC SALES_1;


CREATE TABLE PRODUCT_1(
PROD_ID NUMBER PRIMARY KEY,
PROD_NAME VARCHAR2(10),
PROD_FAMILY VARCHAR2(10));


INSERT ALL
INTO PRODUCT_1 VALUES(300,'LAPTOP','ELCTRONICS')
INTO PRODUCT_1 VALUES(301,'PEN','STATIONARY')
INTO PRODUCT_1 VALUES(302,'WHITEBORD','STATIONARY')
INTO PRODUCT_1 VALUES(303,'LASSI','BEVERAGE')
INTO PRODUCT_1 VALUES(304,'SOAP','GROSSARY')
INTO PRODUCT_1 VALUES(305,'MOUSE','ELCTRONICS')
SELECT * FROM DUAL;

SELECT * FROM PRODUCT_1;


1.WAQTD cutomer wise no of sales and total sales amount and no of products.
2.WAQTD city wise no of customers and no of stores.

SELECT A.CUST_NAME,A.CUST_COUNT,B.STORE_COUNT
FROM (SELECT CITY_NAME ,COUNT(CUST_ID) CUST_COUNT
      FROM CITY C,CUSTOMER CUST
      WHERE C.CITY_ID=CUST.CITY_ID
      GROUP BY CITY_NAME) A,
     SELECT CITY_NAME,COUNT(STORE_ID) STORE_COUNT
     FROM CITY C,STORE S
     WHERE C.CITY_ID=S.CITY_ID
     GROUP BY CITY_NAME) B
WHERE A.CUST_NAME=B.CUST_NAME;

3.Display city which have both customer and stores.

SELECT CITY_NAME 
FROM CITY
WHERE CITY_ID IN (SELECT CITY_ID 
                  FROM CUSTOMER)

INTERSECT

SELECT CITY_NAME 
FROM CITY
WHERE CITY_ID IN (SELECT CITY_ID
                  FROM STORES);
                  
4.Display store names that sells product laptop.

SELECT STORE_NAME 
FROM STORE
WHERE PROD_ID IN (SELECT PROD_ID
                  FROM PRODUCT 
                  WHERE PROD_NAME='LAPTOP');
                  
5.Display city name which have customer but not stores.
SELECT CITY_NAME 
FROM CITY2
WHERE CITY_ID IN (SELECT CITY_ID
                  FROM CUSTOMER2
                  WHERE CUST_ID NOT IN (SELECT CUST_ID 
                                        FROM STORE));
6.Display 'KARNATAKA,BHOPAL' AS
    STATE    KARNATAKA
    CAPITAL  BHOPAL
    
    
select 'state',substr('Karnataka,BHOPAL',1,instr('Karnataka,BHOPAL',',')-1) from dual
UNION
select 'capital',substr('Karnataka,BHOPAL',instr('Karnataka,BHOPAL',',')+1) from dual;








select round(MONTHS_BETWEEN(sysdate,to_date('18-SEP-1996','DD-MON-YYYY'))/12,1)||' Yrs' from dual;

5.Display the day of last day of current year.
SELECT TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'YY'),12)-1,'day')
FROM DUAL;



/*SELECT to_char(trunc(add_months(SYSDATE,12)-1),'day')
FROM DUAL;*/



--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

1.Display the city name that do not have any female actors.

SELECT CITY_NAME
FROM  CITY
WHERE CITY_ID NOT IN  (SELECT CITY_ID FROM ACTOR
                      WHERE CUST_GENDER='FEMALE');
					  
2.Display the actor names whose age is more than 60.

SELECT ANAME
FROM ACTOR
WHERE MONTHS_BETWEEN(ACT_SINCE,CUST_DOB)>60;

3.Display the actors who have been acting right from age of 10.

SELECT ANAME
FROM ACTOR 
WHERE TRUNC(MONTHS_BETWEEN(ACT_SINCE,CUST_DOB)/12) BETWEEN 10 AND 11;

4.Display the movie names that were released in last quarter.

SELECT MNAME FROM MOVIE
WHERE TO_CHAR(REL_DATE,'Q')=4;

5.Display the day of the last day of current year.

SELECT TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'YYYY'),12)-1,'DAY')
FROM DUAL;

6.Display the year wise actor name who played the smallest or shortest role in a movie.
7.Display the actor name who played more than one role in the same movie.

SELECT ANAME
FROM ACTOR A,CAST C
WHERE A.ACT_ID=C.ACT_ID
GROUP BY A.ANAME
HAVING COUNT(ROLE_NAME)>1;
                 
8.Display the movie names that had the maximum no. of roles.

SELECT MOV_NAME
FROM MOVIE M,CAST C
WHERE M.MOV_ID=C.MOV_ID
GROUP BY MOV_NAME
HAVING COUNT(ROLE_NAME)=(SELECT MAX(COUNT(ROLE_NAME)
                         FROM CAST C;
                         
                         

9.Display the cities that have more no. of ame artists than city BHOPAL.


 SELECT CITY_NAME, COUNT(ACT_ID)
FROM CITY_1 C1, ACTOR A1
WHERE A1.ACT_GENDER='MALE'
GROUP BY C1.CITY_NAME
HAVING COUNT(A1.ACT_ID)>(SELECT COUNT(ACT_ID)
                        FROM ACTOR A2, CITY_1 C2
                        WHERE A2.CITY_ID = C2.CITY_ID
                        AND C2.CITY_NAME='Bangalure'
                        GROUP BY C2.CITY_NAME);               
				
10.Display the movie genre wise no. of movies and no. of costs.  

SELECT A1.GENRE,A1.MOV_COUNT,B1.CAST_COUNT 
FROM
     (SELECT GENRE,COUNT(MOV_ID) MOV_COUNT FROM MOVIE
      GROUP BY GENRE) A1,
      (SELECT  GENRE,COUNT(CAST_ID) CAST_COUNT 
	  FROM MOVIE M JOIN CAST C 
	  ON M.MOV_ID=C.MOV_ID
	  GROUP BY GENRE) B1
       
 WHERE A1.GENRE=B1.GENRE;					   


